language: go

os:
  - linux
  - osx

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

  exclude:
    - os: osx
      go: 1.6.x

env:
  global:
    GO111MODULE=on

notifications:
  email:
    on_success: change
    on_failure: always
